# Generated by Django 2.2.6 on 2019-10-22 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Coloque o código da matéria, como consta no SIAC', max_length=10)),
                ('nome', models.CharField(help_text='Coloque o nome da matéria, como consta no SIAC', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dia_horario', models.DateTimeField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenca.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField()),
                ('total_aulas', models.PositiveIntegerField()),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenca.Materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='presenca.Pessoa')),
                ('curso', models.CharField(choices=[('c', 'Ciência da Computação'), ('s', 'Sistemas de Informação'), ('l', 'Licenciatura em Computação'), ('e', 'Engenharia da Computação')], help_text='Selecione seu curso', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='presenca.Pessoa')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(to='presenca.Aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenca.Professor'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenca.Aluno'),
        ),
    ]
